export const ADD_POST = 'ADD_POST';
export const ADD_PROJECT = 'ADD_PROJECT';
export const CHANGE_SELECTED_POST = 'CHANGE_SELECTED_POST';
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POSTS = 'ADD_POSTS';
export const ADD_SELECTED_POST = 'ADD_SELECTED_POST';
export const DELETE_POST = 'DELETE_POST';
export const ADD_SELECTED_PROJECT = 'ADD_SELECTED_PROJECT';
export const CHANGE_EXPERT_STATUS = 'CHANGE_EXPERT_STATUS';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

export const HISTORY_ADD = 'HISTORY_ADD';
export const HISTORY_GET = 'HISTORY_GET';
